// presentation/src/gui/tauri-gui-solid/src/components/SnippetList.tsx
import { createStore } from "solid-js/store";
import { Snippet, Tag } from "../types";
import { createEffect, For } from "solid-js";

export function SnippetList(props: { data: Array<Snippet> }) {
    const [data, setData] = createStore([] as Snippet[]);

    createEffect(() => {
        setData(props.data);
    });

    return (
        <>
        <div class="snippet-container">
            <For each={data}>
                {(item: Snippet) => (
                    <sl-card class="snippet-item">
                        <div slot="header">
                            {item.title}
                        </div>
                        <div slot="footer">
                            <For each={item.tags}>
                                {(tag: Tag) => (
                                    <>{tag.title}</>
                                )}
                            </For>
                        </div>
                        {item.text}
                    </sl-card>
                )}
            </For>
        </div>
        </>
    );
}

// presentation/src/gui/tauri-gui/frontends/lit-solo/src/components/snippet_list.ts
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';

import mainStyles from '../styles/mainStyle.js';

import { Snippet } from '../types.js';
@customElement('snippet-list')
export class Comp extends LitElement {
  static styles = [
    mainStyles,
    css `
      :host {
        display: block;
      }
    `
  ];

  @property({type: Array})
  snippets: Array<Snippet> = [];

  connectedCallback(): void {
    super.connectedCallback();
    console.log("connectedCallback");
  }
  render() {
    return html`
        <div class="snippet-container">
            ${this.snippets.map((snippet) => 
                html`
                    <sl-card class="snippet-item">
                        <div slot="header">
                            ${snippet.title}
                        </div>
                        <div slot="footer">
                            ${snippet.tags.map((tag) =>
                                html`<div>${tag.title}</div>`
                            )}
                        </div>
                        ${snippet.text}
                    </sl-card>
                `
            )}
        </div>
    `;
  }
}
